// File generated by Antigravity AI based on google-services.json
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you are using the Android configuration.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you are using the Android configuration.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you are using the Android configuration.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you are using the Android configuration.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you are using the Android configuration.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx4153O0PmVjXfxv7k-fAEzX51syP9_ek',
    appId: '1:247764122338:android:5d10476473ee3e5f9dbcbb',
    messagingSenderId: '247764122338',
    projectId: 'ar-ml-homeviz-ba4c4',
    storageBucket: 'ar-ml-homeviz-ba4c4.firebasestorage.app',
    databaseURL: 'https://ar-ml-homeviz-ba4c4-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
